### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by xpathexception** [inex1327/MyCarfinder#4]
https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/ApiCaller.java#L32

Именование методов с заглавной буквы нарушает соглашение об именовании в Java (https://www.geeksforgeeks.org/java-naming-conventions/)

**Comment by laqr** [comment]
И еще:
https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/CarsData/Media.java#L5

Подобное именование нарушает соглашение из https://github.com/inex1327/MyCarfinder/issues/4#issue-370083389.  
Стоит использовать https://google.github.io/gson/apidocs/com/google/gson/annotations/SerializedName.html

**Comment by xpathexception** [comment]
https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/Fragments/SetMakeFilter.java#L21

Имя класса, унаследованного от `Fragment`, должно явно указывать на наследование от класса `Fragment`, аналогично SetFilters**Fragment**.

**Comment by xpathexception** [comment]
https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/Fragments/SetMakeFilter.java#L32

Имя layout-файла должно соответствовать имени фрагмента.

Например для класса `SetMakeFilterFragment` layout-файл должен именоваться как `fragment_set_make_filter`
