### ISSUE TITLE
Дублирование коллекций

### ISSUE THREAD

**Issue by xpathexception** [inex1327/MyCarfinder#8]
https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/RuntimeStorage.java#L16-L17

Использование двух коллекций избыточно, поскольку их содержимое полностью дублируется

https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/MainActivity.java#L162-L165

**Comment by inex1327** [comment]
@xpathexception, это заглушка для новой фичи, которой еще нет. Планируется, что фильтров будет сильно больше(все фильтры должны содержаться в `allAvailableFilters`) и можно будет отображать только используемые фильтры. А сам выбор и назначение фильтров будет происходить в другом фрагменте, из которого и будет заполняться коллекция `filtersInterfaceArrayMap`.

> [MyCarfinder/app/src/main/java/com/example/inex1/mycarfinderv2/RuntimeStorage.java](https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/RuntimeStorage.java#L16-L17)
> 
> Lines 16 to 17 in [e103c11](/inex1327/MyCarfinder/commit/e103c1131c69f4da496e118f93a387dc6913018f)
> 
>  public ArrayList<FiltersInterface> allAvailableFilters = new ArrayList<>(); 
>  public ArrayMap<String, FiltersInterface> filtersInterfaceArrayMap = new ArrayMap<>(); 
> Использование двух коллекций избыточно, поскольку их содержимое полностью дублируется
> 
> [MyCarfinder/app/src/main/java/com/example/inex1/mycarfinderv2/MainActivity.java](https://github.com/inex1327/MyCarfinder/blob/e103c1131c69f4da496e118f93a387dc6913018f/app/src/main/java/com/example/inex1/mycarfinderv2/MainActivity.java#L162-L165)
> 
> Lines 162 to 165 in [e103c11](/inex1327/MyCarfinder/commit/e103c1131c69f4da496e118f93a387dc6913018f)
> 
>  storage.allAvailableFilters.add(makeFilter);//TODO не забываем добавлять новые доступные фильтры тут 
>  for (FiltersInterface i: storage.allAvailableFilters) { 
>      storage.filtersInterfaceArrayMap.put(i.getKey(),i); 
>  }
